var dir_af981ede765f3bf6ce3128ed45449710 =
[
    [ "syscalls", "dir_c36e60cdee665e285025f4c8b40561bf.html", "dir_c36e60cdee665e285025f4c8b40561bf" ],
    [ "app_data_alignment.ld", "app__data__alignment_8ld_source.html", null ],
    [ "app_smem.ld", "app__smem_8ld_source.html", null ],
    [ "app_smem_aligned.ld", "app__smem__aligned_8ld_source.html", null ],
    [ "app_smem_unaligned.ld", "app__smem__unaligned_8ld_source.html", null ],
    [ "autoconf.h", "autoconf_8h_source.html", null ],
    [ "device_extern.h", "device__extern_8h_source.html", null ],
    [ "devicetree_fixups.h", "devicetree__fixups_8h_source.html", null ],
    [ "devicetree_unfixed.h", "devicetree__unfixed_8h_source.html", null ],
    [ "driver-validation.h", "driver-validation_8h_source.html", null ],
    [ "kobj-types-enum.h", "kobj-types-enum_8h_source.html", null ],
    [ "ncs_version.h", "ncs__version_8h_source.html", null ],
    [ "offsets.h", "offsets_8h_source.html", null ],
    [ "otype-to-size.h", "otype-to-size_8h_source.html", null ],
    [ "otype-to-str.h", "otype-to-str_8h_source.html", null ],
    [ "snippets-data-sections.ld", "snippets-data-sections_8ld_source.html", null ],
    [ "snippets-noinit.ld", "snippets-noinit_8ld_source.html", null ],
    [ "snippets-ram-sections.ld", "snippets-ram-sections_8ld_source.html", null ],
    [ "snippets-ramfunc-section.ld", "snippets-ramfunc-section_8ld_source.html", null ],
    [ "snippets-rodata.ld", "snippets-rodata_8ld_source.html", null ],
    [ "snippets-rom-start.ld", "snippets-rom-start_8ld_source.html", null ],
    [ "snippets-rwdata.ld", "snippets-rwdata_8ld_source.html", null ],
    [ "snippets-sections.ld", "snippets-sections_8ld_source.html", null ],
    [ "syscall_dispatch.c", "syscall__dispatch_8c_source.html", null ],
    [ "syscall_list.h", "syscall__list_8h_source.html", null ],
    [ "version.h", "version_8h_source.html", null ]
];